/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppTransactionsRouteImport } from './routes/app/transactions'
import { Route as AppFeedbackRouteImport } from './routes/app/feedback'
import { Route as AppFaqRouteImport } from './routes/app/faq'
import { Route as AppAvailabilityRouteImport } from './routes/app/availability'
import { Route as AdminVouchersRouteImport } from './routes/admin/vouchers'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminHealthCheckRouteImport } from './routes/admin/health-check'
import { Route as AdminFeedbackRouteImport } from './routes/admin/feedback'
import { Route as AdminFailedUploadsRouteImport } from './routes/admin/failed-uploads'
import { Route as AdminEvalsRouteImport } from './routes/admin/evals'
import { Route as AdminBannedRouteImport } from './routes/admin/banned'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppFaqRoute = AppFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AppRoute,
} as any)
const AppAvailabilityRoute = AppAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => AppRoute,
} as any)
const AdminVouchersRoute = AdminVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthCheckRoute = AdminHealthCheckRouteImport.update({
  id: '/health-check',
  path: '/health-check',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFailedUploadsRoute = AdminFailedUploadsRouteImport.update({
  id: '/failed-uploads',
  path: '/failed-uploads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEvalsRoute = AdminEvalsRouteImport.update({
  id: '/evals',
  path: '/evals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannedRoute = AdminBannedRouteImport.update({
  id: '/banned',
  path: '/banned',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/banned': typeof AdminBannedRoute
  '/admin/evals': typeof AdminEvalsRoute
  '/admin/failed-uploads': typeof AdminFailedUploadsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/health-check': typeof AdminHealthCheckRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/app/availability': typeof AppAvailabilityRoute
  '/app/faq': typeof AppFaqRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/banned': typeof AdminBannedRoute
  '/admin/evals': typeof AdminEvalsRoute
  '/admin/failed-uploads': typeof AdminFailedUploadsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/health-check': typeof AdminHealthCheckRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/app/availability': typeof AppAvailabilityRoute
  '/app/faq': typeof AppFaqRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/banned': typeof AdminBannedRoute
  '/admin/evals': typeof AdminEvalsRoute
  '/admin/failed-uploads': typeof AdminFailedUploadsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/health-check': typeof AdminHealthCheckRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/app/availability': typeof AppAvailabilityRoute
  '/app/faq': typeof AppFaqRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/admin/banned'
    | '/admin/evals'
    | '/admin/failed-uploads'
    | '/admin/feedback'
    | '/admin/health-check'
    | '/admin/messages'
    | '/admin/settings'
    | '/admin/vouchers'
    | '/app/availability'
    | '/app/faq'
    | '/app/feedback'
    | '/app/transactions'
    | '/admin/'
    | '/app/'
    | '/admin/users/$userId'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/banned'
    | '/admin/evals'
    | '/admin/failed-uploads'
    | '/admin/feedback'
    | '/admin/health-check'
    | '/admin/messages'
    | '/admin/settings'
    | '/admin/vouchers'
    | '/app/availability'
    | '/app/faq'
    | '/app/feedback'
    | '/app/transactions'
    | '/admin'
    | '/app'
    | '/admin/users/$userId'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/admin/banned'
    | '/admin/evals'
    | '/admin/failed-uploads'
    | '/admin/feedback'
    | '/admin/health-check'
    | '/admin/messages'
    | '/admin/settings'
    | '/admin/vouchers'
    | '/app/availability'
    | '/app/faq'
    | '/app/feedback'
    | '/app/transactions'
    | '/admin/'
    | '/app/'
    | '/admin/users/$userId'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/feedback': {
      id: '/app/feedback'
      path: '/feedback'
      fullPath: '/app/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/faq': {
      id: '/app/faq'
      path: '/faq'
      fullPath: '/app/faq'
      preLoaderRoute: typeof AppFaqRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/availability': {
      id: '/app/availability'
      path: '/availability'
      fullPath: '/app/availability'
      preLoaderRoute: typeof AppAvailabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/vouchers': {
      id: '/admin/vouchers'
      path: '/vouchers'
      fullPath: '/admin/vouchers'
      preLoaderRoute: typeof AdminVouchersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health-check': {
      id: '/admin/health-check'
      path: '/health-check'
      fullPath: '/admin/health-check'
      preLoaderRoute: typeof AdminHealthCheckRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/failed-uploads': {
      id: '/admin/failed-uploads'
      path: '/failed-uploads'
      fullPath: '/admin/failed-uploads'
      preLoaderRoute: typeof AdminFailedUploadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/evals': {
      id: '/admin/evals'
      path: '/evals'
      fullPath: '/admin/evals'
      preLoaderRoute: typeof AdminEvalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banned': {
      id: '/admin/banned'
      path: '/banned'
      fullPath: '/admin/banned'
      preLoaderRoute: typeof AdminBannedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBannedRoute: typeof AdminBannedRoute
  AdminEvalsRoute: typeof AdminEvalsRoute
  AdminFailedUploadsRoute: typeof AdminFailedUploadsRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminHealthCheckRoute: typeof AdminHealthCheckRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminVouchersRoute: typeof AdminVouchersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannedRoute: AdminBannedRoute,
  AdminEvalsRoute: AdminEvalsRoute,
  AdminFailedUploadsRoute: AdminFailedUploadsRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminHealthCheckRoute: AdminHealthCheckRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminVouchersRoute: AdminVouchersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAvailabilityRoute: typeof AppAvailabilityRoute
  AppFaqRoute: typeof AppFaqRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAvailabilityRoute: AppAvailabilityRoute,
  AppFaqRoute: AppFaqRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
