/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VouchersRouteImport } from './routes/vouchers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HealthCheckRouteImport } from './routes/health-check'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FailedUploadsRouteImport } from './routes/failed-uploads'
import { Route as EvalsRouteImport } from './routes/evals'
import { Route as BannedRouteImport } from './routes/banned'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'

const VouchersRoute = VouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthCheckRoute = HealthCheckRouteImport.update({
  id: '/health-check',
  path: '/health-check',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FailedUploadsRoute = FailedUploadsRouteImport.update({
  id: '/failed-uploads',
  path: '/failed-uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalsRoute = EvalsRouteImport.update({
  id: '/evals',
  path: '/evals',
  getParentRoute: () => rootRouteImport,
} as any)
const BannedRoute = BannedRouteImport.update({
  id: '/banned',
  path: '/banned',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banned': typeof BannedRoute
  '/evals': typeof EvalsRoute
  '/failed-uploads': typeof FailedUploadsRoute
  '/feedback': typeof FeedbackRoute
  '/health-check': typeof HealthCheckRoute
  '/settings': typeof SettingsRoute
  '/vouchers': typeof VouchersRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banned': typeof BannedRoute
  '/evals': typeof EvalsRoute
  '/failed-uploads': typeof FailedUploadsRoute
  '/feedback': typeof FeedbackRoute
  '/health-check': typeof HealthCheckRoute
  '/settings': typeof SettingsRoute
  '/vouchers': typeof VouchersRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/banned': typeof BannedRoute
  '/evals': typeof EvalsRoute
  '/failed-uploads': typeof FailedUploadsRoute
  '/feedback': typeof FeedbackRoute
  '/health-check': typeof HealthCheckRoute
  '/settings': typeof SettingsRoute
  '/vouchers': typeof VouchersRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/banned'
    | '/evals'
    | '/failed-uploads'
    | '/feedback'
    | '/health-check'
    | '/settings'
    | '/vouchers'
    | '/users/$userId'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banned'
    | '/evals'
    | '/failed-uploads'
    | '/feedback'
    | '/health-check'
    | '/settings'
    | '/vouchers'
    | '/users/$userId'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/banned'
    | '/evals'
    | '/failed-uploads'
    | '/feedback'
    | '/health-check'
    | '/settings'
    | '/vouchers'
    | '/users/$userId'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BannedRoute: typeof BannedRoute
  EvalsRoute: typeof EvalsRoute
  FailedUploadsRoute: typeof FailedUploadsRoute
  FeedbackRoute: typeof FeedbackRoute
  HealthCheckRoute: typeof HealthCheckRoute
  SettingsRoute: typeof SettingsRoute
  VouchersRoute: typeof VouchersRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vouchers': {
      id: '/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof VouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-check': {
      id: '/health-check'
      path: '/health-check'
      fullPath: '/health-check'
      preLoaderRoute: typeof HealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/failed-uploads': {
      id: '/failed-uploads'
      path: '/failed-uploads'
      fullPath: '/failed-uploads'
      preLoaderRoute: typeof FailedUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evals': {
      id: '/evals'
      path: '/evals'
      fullPath: '/evals'
      preLoaderRoute: typeof EvalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banned': {
      id: '/banned'
      path: '/banned'
      fullPath: '/banned'
      preLoaderRoute: typeof BannedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BannedRoute: BannedRoute,
  EvalsRoute: EvalsRoute,
  FailedUploadsRoute: FailedUploadsRoute,
  FeedbackRoute: FeedbackRoute,
  HealthCheckRoute: HealthCheckRoute,
  SettingsRoute: SettingsRoute,
  VouchersRoute: VouchersRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
